---
services:
  inkfra-server:
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - backend
    env_file:
      - .env
  inkfra-db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql
    env_file:
      - .env

networks:
  backend:
